FORMAT: 1A
HOST: http://www.google.com

# domojs
Domojs helps you manage your home. 


## Device Categories [/api/devices]
### List all device categories [GET]
+ Response 200 (application/json)

        [
            {
                "name":"gpio",
                "length":1,
                "url":"/api/devices/gpio"
            },
            {
                "name":"remote",
                "length":10,
                "url":"/api/devices/remote"
            },
            {
                "name":"switch",
                "length":2,
                "url":"/api/devices/switch"
            },
            {
                "name":"analogic",
                "length":1,
                "url":"/api/devices/analogic"
            },
            {
                "name":"values",
                "length":1,
                "url":"/api/devices/values"
            },
            {
                "name":"pvr",
                "length":1,
                "url":"/api/devices/pvr"
            }
        ]

## Device category [/api/devices/{category}]
A single category with all the devices related to it

+ Parameters
    + category (required, string, `switch`) ... Device `category` to get devices with. Has example value.

### Retrieve a devices collection [GET]
+ Response 200 (application/json)

        [
            {
                "name":"pioneer.power",
                "length":2,
                "url":"/api/devices/switch/pioneer.power"
            },
            {
                "name":"pioneer.mute",
                "length":2,
                "url":"/api/devices/switch/pioneer.mute"
            }
        ]
        
        
## Device commands [/api/devices/{category}/{name}]
A single device with all its commands

+ Parameters
    + category (required, string, `switch`) ... Device `category` to get devices with. Has example value.
    + name (required, string, `pioneer.power`) ... Device `name` to get commands on. Has example value.

### Retrieve a commands collection [GET]
+ Response 200 (application/json)

        [
            {
                "name":"on",
                "url":"/api/pioneer/PO"
            },
            {
                "name":"off",
                "url":"/api/pioneer/PF"
            }
        ]


## Execute command [/api/devices/{category}/{name}/{cmd}]
A single device with all its commands

+ Parameters
    + category (required, string, `switch`) ... Device `category` to get devices with. Has example value.
    + name (required, string, `pioneer.power`) ... Device `name` to get commands on. Has example value.
    + cmd (required, string, `on`) ... `cmd` to execute on specified device named `name`. Has example value.

### Retrieve a commands collection [GET]
+ Response 200 (text/plain)