// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/vinyl-buffer/vinyl-buffer.d.ts
declare module "vinyl-buffer" {
    namespace buffer {
        interface Buffer {
            (): NodeJS.ReadWriteStream;
        }
    }

    var buffer: buffer.Buffer;

    export = buffer;
}
